version: '3.8'

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-devpassword}
      - POSTGRES_DB=crewai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  gradio:
    build:
      context: .
      dockerfile: apps/gradio/Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./apps/gradio:/app
    environment:
      - REDIS_URL=redis://redis:6379
      - API_URL=http://localhost:8000
      - WS_URL=ws://localhost:8001
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - redis
      - ollama

volumes:
  postgres-data:
  redis-data:
  ollama-data: